#pragma once
#include "port.hpp"

class JackTransport;

// A JACK MIDI output port. Owns the registration lifecycle on the JackTransport
// (register on construction / when JACK is up, unregister on destruction). Sample-
// accurate note playback is generated by JackTransport's RT engine, so this port is
// NOT soft-sequenced; its send methods only queue one-shot messages (program/bank
// changes, panics) for the next RT cycle.
class JackPort : public Port {
public:
    JackPort(JackTransport* jack, std::string name);
    ~JackPort() override;

    void rename(const std::string& n) override;

    MidiBackend backend()       const override { return MidiBackend::Jack; }
    bool        softSequenced() const override { return false; }

    void noteOn (int ch, int pitch, int vel) override;
    void noteOff(int ch, int pitch)          override;
    void cc     (int ch, int num, int val)   override;
    void pitchBend(int ch, int value14)      override;
    void programChange(int ch, int bankMsb, int bankLsb, int program) override;

private:
    JackTransport* jack_;
};
