# Generate luvieVersion.hpp from the current git state.
#
# Run as a script at *build* time (not configure time) so the embedded version
# tracks new commits/tags without needing to re-run CMake. The header is only
# rewritten when the version string actually changes, so unchanged builds don't
# needlessly recompile everything that includes it.
#
# Expected -D variables: SRC_DIR (source tree, for git), OUT_FILE (header to write).

set(VERSION "unknown")

find_package(Git QUIET)
if(GIT_FOUND)
    # --tags:   consider lightweight tags too, not just annotated ones
    # --dirty:  append "-dirty" when the working tree has uncommitted changes
    # --always: fall back to a bare commit hash if there are no tags yet
    execute_process(
        COMMAND ${GIT_EXECUTABLE} describe --tags --dirty --always
        WORKING_DIRECTORY ${SRC_DIR}
        OUTPUT_VARIABLE GIT_DESCRIBE
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
        RESULT_VARIABLE GIT_RESULT
    )
    if(GIT_RESULT EQUAL 0 AND GIT_DESCRIBE)
        set(VERSION "${GIT_DESCRIBE}")
    endif()
endif()

set(NEW_CONTENT "// Generated by cmake/GitVersion.cmake at build time. Do not edit.\n#pragma once\n#define LUVIE_VERSION \"${VERSION}\"\n")

# Only write if the content changed, to avoid spurious recompiles.
set(OLD_CONTENT "")
if(EXISTS "${OUT_FILE}")
    file(READ "${OUT_FILE}" OLD_CONTENT)
endif()
if(NOT OLD_CONTENT STREQUAL NEW_CONTENT)
    file(WRITE "${OUT_FILE}" "${NEW_CONTENT}")
endif()
